server:
  port: 8080
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: iliceworks-be

  cache:
    type: redis
    data:
      redis:
        host: redis-server
        port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  datasource:
    #url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://my-sql-server:3306/mydatabase?serverTimezone=UTC&characterEncoding=UTF-8
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
    ##username: root
    ##password: 1234
    ##url: jdbc:mysql://localhost:9906/iliceworks?serverTimezone=UTC&characterEncoding=UTF-8
    ##driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    #username: gnues0225@gmail.com
    #password: mpry mpad stzy dfot
    username: rhkdgh99093015@gmail.com
    password: jnzz tafg pcgn vukv
    properties:
      smtp:
        auth: true
        timeout: 5000
        starttls:
          enable: true
  cloud:
    compatibility-verifier:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs  # API 문서 기본 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로

token:
  secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
  access-token-expiration: 600000  # 10분 (밀리초)
  refresh-token-expiration: 1  # 1시간 (시간)
  #refresh-token-expiration: 1  # 1시간 (시간)

firebase:
  storage:
    bucket-name: "myproject-2f867.appspot.com"
    #json-path: "src/main/resources/serviceAccountKey.json"
    json-path: "/app/serviceAccountKey.json"

ai:
  flask-url: "http://34.22.92.60:5000"

google:
  api-key: AIzaSyCKx26giOQwQlhNF9BNBe38O08T2SCv0qU
  google-korea-holiday-id: ko.south_korea#holiday@group.v.calendar.google.com

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: my-spring-app  # 원하는 앱 이름
    enable:
      http: true   # HTTP 요청 메트릭 활성화 (이게 없으면 http_server_requests_*가 안 보일 수 있음)
      jvm: true
      system: true